name: docker-test

on:
  push:
    branches:
      - "main"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Checkout And Build
        run: docker compose -f test.compose.yml build
      - name: start containers
        run: docker compose -f test.compose.yml up -d
      - name: Run tests
        run: docker compose -f test.compose.yml exec -it testrunner npm test
      - name: Stop containers
        run: docker compose -f test.compose.yml down
